"""
sage_memory_condenser.py
Watches the active Claude Code conversation JSONL for Sage's session.
When context grows large, extracts a dense Context-Schema.md locally
and sends Sage a peer message to write his journal before things go critical.
Everything stays local -- no data leaves the machine.

Run: python sage_memory_condenser.py
"""

import os
import json
import time
import glob
import re
import urllib.request
import urllib.error
from datetime import datetime

# --- Config ---
PROJECT_DIR = r"C:\Users\krist\.claude\projects\C--Users-krist-Documents-Reeves-Family-claude-peers-mcp--claude-worktrees-gallant-turing-3542d9"
SCHEMA_PATH = r"C:\Users\krist\sage_context_schema.md"
BROKER_URL = "http://localhost:7899"

POLL_INTERVAL = 30       # seconds between checks
WARNING_MB = 80          # alert Sage at this size
SCHEMA_MB = 100          # write schema + alert at this size
SCHEMA_RETRIGGER_MB = 5  # re-write every N MB past threshold
MAX_MESSAGES = 60        # recent messages to include in schema
TAIL_SCAN_MB = 5         # MB from tail to scan for technical facts


def log(msg):
    try:
        print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}")
    except UnicodeEncodeError:
        print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg.encode('ascii', errors='replace').decode()}")


def find_active_jsonl():
    """Return the most recently modified JSONL in the project directory."""
    files = glob.glob(os.path.join(PROJECT_DIR, "*.jsonl"))
    if not files:
        return None
    return max(files, key=os.path.getmtime)


def size_mb(path):
    return os.path.getsize(path) / 1024 / 1024


def extract_messages(jsonl_path, max_messages=60):
    """Pull the last N user/assistant messages from the JSONL file."""
    messages = []
    try:
        with open(jsonl_path, "r", encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                    msg = entry.get("message", {})
                    role = msg.get("role", "")
                    if role not in ("user", "assistant"):
                        continue
                    content = msg.get("content", "")
                    if isinstance(content, list):
                        text = " ".join(
                            c.get("text", "")
                            for c in content
                            if isinstance(c, dict) and c.get("type") == "text"
                        )
                    else:
                        text = str(content)
                    text = text.strip()
                    if text:
                        messages.append({"role": role, "text": text[:600]})
                except Exception:
                    continue
    except Exception as e:
        log(f"Message extract error: {e}")
    return messages[-max_messages:]


def extract_technical_facts(jsonl_path):
    """Scan the tail of the file for file paths, ports, and local URLs."""
    facts = {"paths": set(), "ports": set(), "urls": set()}
    path_re = re.compile(r"[A-Za-z]:\\(?:[^\s'\"<>|*?]+\\)*[^\s'\"<>|*?\\]+")
    port_re = re.compile(r"(?:port\s*[=:]\s*|localhost:)(\d{4,5})", re.IGNORECASE)
    url_re = re.compile(r"http://localhost:\d+\S*")

    try:
        file_size = os.path.getsize(jsonl_path)
        scan_start = max(0, file_size - TAIL_SCAN_MB * 1024 * 1024)
        with open(jsonl_path, "rb") as f:
            f.seek(scan_start)
            chunk = f.read().decode("utf-8", errors="replace")

        for m in path_re.finditer(chunk):
            p = m.group()
            if len(p) < 120 and ".jsonl" not in p and "\\cache\\" not in p.lower():
                facts["paths"].add(p)

        for m in port_re.finditer(chunk):
            facts["ports"].add(m.group(1))

        for m in url_re.finditer(chunk):
            facts["urls"].add(m.group()[:100])

    except Exception as e:
        log(f"Fact extraction error: {e}")

    return {k: sorted(v) for k, v in facts.items()}


def write_schema(jsonl_path, messages, facts):
    """Write sage_context_schema.md — a dense reference for load-in."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    mb = size_mb(jsonl_path)
    fname = os.path.basename(jsonl_path)

    lines = [
        "# Context Schema",
        "",
        f"*Auto-generated by sage_memory_condenser.py — {now}*  ",
        f"*Source: {fname} ({mb:.1f} MB)*",
        "",
        "---",
        "",
        f"## Recent Conversation (last {len(messages)} messages)",
        "",
    ]

    for m in messages:
        label = "**Kristina**" if m["role"] == "user" else "**Sage**"
        text = m["text"].replace("\n", " ").strip()
        lines.append(f"- {label}: {text}")

    lines += [
        "",
        "---",
        "",
        "## Known File Paths",
        "",
    ]
    for p in list(facts["paths"])[:25]:
        lines.append(f"- `{p}`")

    lines += [
        "",
        "## Active Ports",
        "",
    ]
    for p in facts["ports"]:
        lines.append(f"- :{p}")

    lines += [
        "",
        "## Local URLs",
        "",
    ]
    for u in list(facts["urls"])[:15]:
        lines.append(f"- {u}")

    with open(SCHEMA_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    log(f"Schema written -> {SCHEMA_PATH} ({mb:.1f} MB session)")


def get_peers():
    """Return list of active peer dicts from the broker."""
    try:
        payload = json.dumps({"scope": "machine"}).encode()
        req = urllib.request.Request(
            f"{BROKER_URL}/list-peers",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=3) as resp:
            return json.loads(resp.read())
    except Exception as e:
        log(f"list-peers failed: {e}")
        return []


def find_sage_peer(peers):
    """Return the peer ID for Sage's session."""
    for p in peers:
        summary = (p.get("summary") or "").lower()
        pid = (p.get("id") or "").lower()
        if "sage" in summary or "sage" in pid:
            return p["id"]
    return None


def send_to_peer(peer_id, text):
    """Send a message to a specific peer."""
    try:
        payload = json.dumps({
            "from_id": "condenser",
            "to_id": peer_id,
            "text": text,
        }).encode()
        req = urllib.request.Request(
            f"{BROKER_URL}/send-message",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=3):
            pass
        return True
    except Exception as e:
        log(f"send to {peer_id} failed: {e}")
        return False


def alert_sage(mb, schema_written=False):
    """Send Sage a context size alert with instructions."""
    peers = get_peers()
    sage_id = find_sage_peer(peers)

    if schema_written:
        msg = (
            f"[condenser] Context is {mb:.1f} MB. "
            f"Schema written to C:\\Users\\krist\\sage_context_schema.md. "
            f"Write your journal to the vault now — compact is coming."
        )
    else:
        msg = (
            f"[condenser] Context at {mb:.1f} MB — getting large. "
            f"Consider writing journal to vault soon."
        )

    if sage_id:
        if send_to_peer(sage_id, msg):
            log(f"Sage alerted (peer {sage_id}): {mb:.1f} MB")
            return
    # Fall back to all peers if Sage not found
    sent = 0
    for p in peers:
        if send_to_peer(p["id"], msg):
            sent += 1
    if sent:
        log(f"Alert sent to {sent} peer(s) (Sage not identified)")
    else:
        log(f"No peers reachable — alert logged locally: {mb:.1f} MB")


def main():
    log("sage_memory_condenser starting")
    log(f"Project dir : {PROJECT_DIR}")
    log(f"Schema path : {SCHEMA_PATH}")
    log(f"Thresholds  : warn={WARNING_MB}MB, schema={SCHEMA_MB}MB")
    log("All processing is local — no data leaves this machine")

    alerted_warning = False
    last_schema_written_mb = 0.0

    while True:
        try:
            active = find_active_jsonl()
            if not active:
                log("No JSONL found — waiting")
                time.sleep(POLL_INTERVAL)
                continue

            mb = size_mb(active)

            if mb >= WARNING_MB and not alerted_warning:
                log(f"WARNING {mb:.1f} MB — {os.path.basename(active)}")
                alert_sage(mb, schema_written=False)
                alerted_warning = True

            if mb >= SCHEMA_MB and (mb - last_schema_written_mb) >= SCHEMA_RETRIGGER_MB:
                log(f"Threshold reached ({mb:.1f} MB) — extracting schema")
                messages = extract_messages(active, MAX_MESSAGES)
                facts = extract_technical_facts(active)
                write_schema(active, messages, facts)
                alert_sage(mb, schema_written=True)
                last_schema_written_mb = mb

        except Exception as e:
            log(f"Main loop error: {e}")

        time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    main()
